---
title: "MUSA 550 Final Project: An Evaluation on Hong Kong Urban Resiliency to Urban Heat"
subtitle: "Group member: Hang Zhao, George Chen, Ling Chen"
---

## Welcome!


Group final project for the University of Pennsylvania School of Design course, MUSA 550 Geospatial Data Science in Python. 

Our project, centered on enhancing urban resilience in Hong Kong, addresses the critical issues of climate change and the urban heat island effect through the innovative application of Python data science and geography. By leveraging a rich array of geospatial data, including raster images and extensive datasets from the Hong Kong Government and ESRI, we aim to create insightful visualizations that illuminate the complexities of these environmental challenges. This project stands at the forefront of technology and sustainability, employing advanced techniques like cluster analysis to dissect and understand the spatial patterns of heat distribution and environmental impacts within the urban fabric of Hong Kong.

 
::: {.callout-important}
This project is currently in the refinement phase, with ongoing efforts to enhance and update its content on this website. Looking ahead, we plan to implement significant improvements, including the integration of a machine learning predictive model. These forthcoming advancements are aimed at further enriching the project's depth and effectiveness. 
:::

## Find out more

The code for this repository is hosted on our course's GitHub page: [Final Project Github Page](https://github.com/Cyanhang/MUSA550_Fall2023_Final_Project).








 
